### ISSUE TITLE
issue when building app

### ISSUE THREAD

**Issue by fderyckel** [fossunited/mon_school#4]
I was just checking your app as I am interested in education domain. 
See below error message.

flipo@ubuntu-s-1vcpu-2gb-education:~/frappe-bench$ bench build --app monschool                                                                                            

yarn run v1.22.4
warning ../../package.json: No license field
$ FRAPPE_ENV=production node rollup/build.js --app monschool
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js
(node:542893) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at run_build_command_for_app (/home/flipo/frappe-bench/apps/frappe/rollup/build.js:152:27)
    at /home/flipo/frappe-bench/apps/frappe/rollup/build.js:49:4
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:542893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:542893) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fderyckel** [comment]
Wrong command
