### ISSUE TITLE
Server ERROR: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wisharya** [fossunited/mon_school#63]
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![Screenshot 2021-08-19 at 17-43-03 Build](https://user-images.githubusercontent.com/25725389/130066483-35ae0761-7d4b-4ce1-81b0-3df828a8a9c3.png)

**Comment by anandology** [comment]
The following request is failing:

`POST https://mon.school/api/method/frappe.desk.desktop.get_desktop_page`

with this trackback:

```
Traceback (most recent call last):
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 1204, in call
    return fn(*args, **newargs)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 620, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/desk/desktop.py", line 377, in get_desktop_page
    wspace = Workspace(loads(page))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

@pateljannat do you know what is happening? How to resolve this?

**Comment by anandology** [comment]
Upgraded to latest version of frappe, community and mon_school. The issue is still there.
